---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: stable
  interval: 1m0s

